grpc:
  server:
    port: 7080

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update    # dev: update, create-drop / prod: validate 추천
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/pinit_task?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: amqp://${RABBITMQ_HOST}:${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /pinit
    connection-timeout: 5000

path:
  key:
    jwt:
      public: ${HOME}/pinit/keys/jwt-public-key.pem