spring:
  jpa:
    hibernate:
      ddl-auto: validate    # dev: update, create-drop / prod: validate 추천
    open-in-view: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/pinit_task?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: amqp://${RABBITMQ_HOST}:${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /pinit
    connection-timeout: 5000

management:
  server:
    port: 9095
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"


path:
  key:
    jwt:
      public: /etc/keys/jwt-public-key.pem