apiVersion: v1
kind: Service
metadata:
  name: task-metrics-service
  namespace: pinit
spec:
  selector:
    app: pinit-task
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      nodePort: 30096
  type: NodePort
  