name: pinit-task CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: [ arc-runner-set ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Check Docker availability
        run: docker info

      - name: Build & Test
        run: ./gradlew clean generateProto test build

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-artifacts
          if-no-files-found: warn
          path: |
            build/test-results/test/**
            build/reports/tests/test/**
            build/testcontainers-logs/**
